export const STATES: { [key: string]: string } = {
  'alabama': 'al',
  'alaska': 'ak',
  'arizona': 'az',
  'arkansas': 'ar',
  'california': 'ca',
  'colorado': 'co',
  'connecticut': 'ct',
  'delaware': 'de',
  'florida': 'fl',
  'georgia': 'ga',
  'hawaii': 'hi',
  'idaho': 'id',
  'illinois': 'il',
  'indiana': 'in',
  'iowa': 'ia',
  'kansas': 'ks',
  'kentucky': 'ky',
  'louisiana': 'la',
  'maine': 'me',
  'maryland': 'md',
  'massachusetts': 'ma',
  'michigan': 'mi',
  'minnesota': 'mn',
  'mississippi': 'ms',
  'missouri': 'mo',
  'montana': 'mt',
  'nebraska': 'ne',
  'nevada': 'nv',
  'new hampshire': 'nh',
  'new jersey': 'nj',
  'new mexico': 'nm',
  'new york': 'ny',
  'north carolina': 'nc',
  'north dakota': 'nd',
  'ohio': 'oh',
  'oklahoma': 'ok',
  'oregon': 'or',
  'pennsylvania': 'pa',
  'rhode island': 'ri',
  'south carolina': 'sc',
  'south dakota': 'sd',
  'tennessee': 'tn',
  'texas': 'tx',
  'utah': 'ut',
  'vermont': 'vt',
  'virginia': 'va',
  'washington': 'wa',
  'west virginia': 'wv',
  'wisconsin': 'wi',
  'wyoming': 'wy',
  'district of columbia': 'dc',
  'puerto rico': 'pr',
  'al': 'al',
  'ak': 'ak',
  'az': 'az',
  'ar': 'ar',
  'ca': 'ca',
  'co': 'co',
  'ct': 'ct',
  'de': 'de',
  'fl': 'fl',
  'ga': 'ga',
  'hi': 'hi',
  'id': 'id',
  'il': 'il',
  'in': 'in',
  'ia': 'ia',
  'ks': 'ks',
  'ky': 'ky',
  'la': 'la',
  'me': 'me',
  'md': 'md',
  'ma': 'ma',
  'mi': 'mi',
  'mn': 'mn',
  'ms': 'ms',
  'mo': 'mo',
  'mt': 'mt',
  'ne': 'ne',
  'nv': 'nv',
  'nh': 'nh',
  'nj': 'nj',
  'nm': 'nm',
  'ny': 'ny',
  'nc': 'nc',
  'nd': 'nd',
  'oh': 'oh',
  'ok': 'ok',
  'or': 'or',
  'pa': 'pa',
  'ri': 'ri',
  'sc': 'sc',
  'sd': 'sd',
  'tn': 'tn',
  'tx': 'tx',
  'ut': 'ut',
  'vt': 'vt',
  'va': 'va',
  'wa': 'wa',
  'wv': 'wv',
  'wi': 'wi',
  'wy': 'wy',
  'dc': 'dc',
  'pr': 'pr',
};

/**
 * USPS Official Standard Street Suffix Abbreviations
 * Source: https://pe.usps.com/text/pub28/pub28apc_002.htm
 */
export const USPS_STREET_SUFFIXES: Array<{
  primary: string;
  common: string[];
  standard: string;
}> = [
  { primary: "alley", common: ["allee", "ally"], standard: "aly" },
  { primary: "anex", common: ["annx"], standard: "anx" },
  { primary: "annex", common: [], standard: "anx" },
  { primary: "arcade", common: ["arc"], standard: "arc" },
  { primary: "avenue", common: ["av", "ave", "aven", "avenu", "avn", "avnue"], standard: "ave" },
  { primary: "bayou", common: ["bayoo"], standard: "byu" },
  { primary: "beach", common: ["bch"], standard: "bch" },
  { primary: "bend", common: ["bend"], standard: "bnd" },
  { primary: "bluff", common: ["blf", "bluf"], standard: "blf" },
  { primary: "bluffs", common: ["bluffs"], standard: "blfs" },
  { primary: "bottom", common: ["bot", "bottm"], standard: "btm" },
  { primary: "boulevard", common: ["blvd", "boul", "boulv"], standard: "blvd" },
  { primary: "branch", common: ["br", "brnch"], standard: "br" },
  { primary: "bridge", common: ["brdge"], standard: "brg" },
  { primary: "brook", common: ["brk"], standard: "brk" },
  { primary: "brooks", common: ["brooks"], standard: "brks" },
  { primary: "burg", common: ["burg"], standard: "bg" },
  { primary: "burgs", common: ["burgs"], standard: "bgs" },
  { primary: "bypass", common: ["byp", "bypa", "bypas", "byps"], standard: "byp" },
  { primary: "camp", common: ["camp", "cp", "cmp"], standard: "cp" },
  { primary: "canyon", common: ["cany", "cnyn"], standard: "cyn" },
  { primary: "cape", common: ["cape"], standard: "cpe" },
  { primary: "causeway", common: ["causwa"], standard: "cswy" },
  { primary: "center", common: ["cen", "cent", "centr", "centre", "cnter", "cntr"], standard: "ctr" },
  { primary: "centers", common: ["centers"], standard: "ctrs" },
  { primary: "circle", common: ["cir", "circ", "circl", "crcl", "crcle"], standard: "cir" },
  { primary: "circles", common: ["circles"], standard: "cirs" },
  { primary: "cliff", common: ["clf"], standard: "clf" },
  { primary: "cliffs", common: ["clfs"], standard: "clfs" },
  { primary: "club", common: ["clb"], standard: "clb" },
  { primary: "common", common: ["common"], standard: "cmn" },
  { primary: "commons", common: ["commons"], standard: "cmns" },
  { primary: "corner", common: ["cor"], standard: "cor" },
  { primary: "corners", common: ["corners"], standard: "cors" },
  { primary: "course", common: ["course"], standard: "crse" },
  { primary: "court", common: ["ct"], standard: "ct" },
  { primary: "courts", common: ["cts"], standard: "cts" },
  { primary: "cove", common: ["cv"], standard: "cv" },
  { primary: "coves", common: ["cvs"], standard: "cvs" },
  { primary: "creek", common: ["crk"], standard: "crk" },
  { primary: "crescent", common: ["cres", "crsent", "crsnt"], standard: "cres" },
  { primary: "crest", common: ["crst"], standard: "crst" },
  { primary: "crossing", common: ["crssng"], standard: "xing" },
  { primary: "crossroad", common: ["crossroad"], standard: "xrd" },
  { primary: "crossroads", common: ["crossroads"], standard: "xrds" },
  { primary: "curve", common: ["curv"], standard: "curv" },
  { primary: "dale", common: ["dl"], standard: "dl" },
  { primary: "dam", common: ["dm"], standard: "dm" },
  { primary: "divide", common: ["dv", "dvd"], standard: "dv" },
  { primary: "drive", common: ["dr", "driv", "drv"], standard: "dr" },
  { primary: "drives", common: ["drs"], standard: "drs" },
  { primary: "estate", common: ["est"], standard: "est" },
  { primary: "estates", common: ["ests"], standard: "ests" },
  { primary: "expressway", common: ["exp", "expr", "express", "expw"], standard: "expy" },
  { primary: "extension", common: ["ext", "extn", "extnsn"], standard: "ext" },
  { primary: "extensions", common: ["exts"], standard: "exts" },
  { primary: "fall", common: ["fall"], standard: "fall" },
  { primary: "falls", common: ["fls"], standard: "fls" },
  { primary: "ferry", common: ["frry"], standard: "fry" },
  { primary: "field", common: ["fld"], standard: "fld" },
  { primary: "fields", common: ["flds"], standard: "flds" },
  { primary: "flat", common: ["flt"], standard: "flt" },
  { primary: "flats", common: ["flts"], standard: "flts" },
  { primary: "ford", common: ["frd"], standard: "frd" },
  { primary: "fords", common: ["frds"], standard: "frds" },
  { primary: "forest", common: ["frst", "forests"], standard: "frst" },
  { primary: "forge", common: ["frg", "forg"], standard: "frg" },
  { primary: "forges", common: ["frgs"], standard: "frgs" },
  { primary: "fork", common: ["frk"], standard: "frk" },
  { primary: "forks", common: ["frks"], standard: "frks" },
  { primary: "fort", common: ["ft", "frt"], standard: "ft" },
  { primary: "freeway", common: ["freewy", "frway", "frwy"], standard: "fwy" },
  { primary: "garden", common: ["gardn", "grden", "grdn"], standard: "gdn" },
  { primary: "gardens", common: ["gdns", "grdns"], standard: "gdns" },
  { primary: "gateway", common: ["gatewy", "gatway", "gtway"], standard: "gtwy" },
  { primary: "glen", common: ["gln"], standard: "gln" },
  { primary: "glens", common: ["glns"], standard: "glns" },
  { primary: "green", common: ["grn"], standard: "grn" },
  { primary: "greens", common: ["grns"], standard: "grns" },
  { primary: "grove", common: ["grov", "grv"], standard: "grv" },
  { primary: "groves", common: ["grvs"], standard: "grvs" },
  { primary: "harbor", common: ["harb", "harbr", "hbr", "hrbor"], standard: "hbr" },
  { primary: "harbors", common: ["hbrs"], standard: "hbrs" },
  { primary: "haven", common: ["hvn"], standard: "hvn" },
  { primary: "heights", common: ["ht"], standard: "hts" },
  { primary: "highway", common: ["highwy", "hiway", "hiwy", "hway"], standard: "hwy" },
  { primary: "hill", common: ["hl"], standard: "hl" },
  { primary: "hills", common: ["hls"], standard: "hls" },
  { primary: "hollow", common: ["hllw", "hollo", "holw", "holws"], standard: "holw" },
  { primary: "inlet", common: ["inlt"], standard: "inlt" },
  { primary: "island", common: ["is", "islnd"], standard: "is" },
  { primary: "islands", common: ["iss", "islns"], standard: "iss" },
  { primary: "isle", common: ["isle", "isles"], standard: "isle" },
  { primary: "junction", common: ["jct", "jction", "jctn", "junctn", "juncton"], standard: "jct" },
  { primary: "junctions", common: ["jctns", "jcts"], standard: "jcts" },
  { primary: "key", common: ["ky"], standard: "ky" },
  { primary: "keys", common: ["kys"], standard: "kys" },
  { primary: "knoll", common: ["knl", "knol"], standard: "knl" },
  { primary: "knolls", common: ["knls"], standard: "knls" },
  { primary: "lake", common: ["lk"], standard: "lk" },
  { primary: "lakes", common: ["lks"], standard: "lks" },
  { primary: "land", common: ["land"], standard: "land" },
  { primary: "landing", common: ["lndg", "lndng"], standard: "lndg" },
  { primary: "lane", common: ["ln"], standard: "ln" },
  { primary: "light", common: ["lgt"], standard: "lgt" },
  { primary: "lights", common: ["lgts"], standard: "lgts" },
  { primary: "loaf", common: ["lf"], standard: "lf" },
  { primary: "lock", common: ["lck"], standard: "lck" },
  { primary: "locks", common: ["lcks"], standard: "lcks" },
  { primary: "lodge", common: ["ldg", "ldge", "lodg"], standard: "ldg" },
  { primary: "loop", common: ["loop", "loops"], standard: "loop" },
  { primary: "mall", common: ["mall"], standard: "mall" },
  { primary: "manor", common: ["mnr"], standard: "mnr" },
  { primary: "manors", common: ["mnrs"], standard: "mnrs" },
  { primary: "meadow", common: ["mdw", "medows"], standard: "mdw" },
  { primary: "meadows", common: ["mdws"], standard: "mdws" },
  { primary: "mews", common: ["mews"], standard: "mews" },
  { primary: "mill", common: ["ml"], standard: "ml" },
  { primary: "mills", common: ["mls"], standard: "mls" },
  { primary: "mission", common: ["missn", "mssn"], standard: "msn" },
  { primary: "motorway", common: ["motorway"], standard: "mtwy" },
  { primary: "mount", common: ["mnt", "mt"], standard: "mt" },
  { primary: "mountain", common: ["mntain", "mntn", "mountin", "mtin"], standard: "mtn" },
  { primary: "mountains", common: ["mntns"], standard: "mtns" },
  { primary: "neck", common: ["nck"], standard: "nck" },
  { primary: "orchard", common: ["orch", "orchrd"], standard: "orch" },
  { primary: "oval", common: ["ovl"], standard: "oval" },
  { primary: "overpass", common: ["opas"], standard: "opas" },
  { primary: "park", common: ["park", "prk"], standard: "park" },
  { primary: "parks", common: ["parks"], standard: "park" },
  { primary: "parkway", common: ["parkwy", "pkway", "pky"], standard: "pkwy" },
  { primary: "parkways", common: ["pkwys"], standard: "pkwy" },
  { primary: "pass", common: ["pass"], standard: "pass" },
  { primary: "passage", common: ["psge"], standard: "psge" },
  { primary: "path", common: ["path", "paths"], standard: "path" },
  { primary: "pike", common: ["pike", "pikes"], standard: "pike" },
  { primary: "pine", common: ["pne"], standard: "pne" },
  { primary: "pines", common: ["pnes"], standard: "pnes" },
  { primary: "place", common: ["pl"], standard: "pl" },
  { primary: "plain", common: ["pln"], standard: "pln" },
  { primary: "plains", common: ["plns"], standard: "plns" },
  { primary: "plaza", common: ["plz", "plza"], standard: "plz" },
  { primary: "point", common: ["pt"], standard: "pt" },
  { primary: "points", common: ["pts"], standard: "pts" },
  { primary: "port", common: ["prt"], standard: "prt" },
  { primary: "ports", common: ["prts"], standard: "prts" },
  { primary: "prairie", common: ["pr", "prr"], standard: "pr" },
  { primary: "radial", common: ["rad", "radiel"], standard: "radl" },
  { primary: "ramp", common: ["ramp"], standard: "ramp" },
  { primary: "ranch", common: ["rnch", "rnchs"], standard: "rnch" },
  { primary: "rapid", common: ["rpd"], standard: "rpd" },
  { primary: "rapids", common: ["rpds"], standard: "rpds" },
  { primary: "rest", common: ["rst"], standard: "rst" },
  { primary: "ridge", common: ["rdg", "rdge"], standard: "rdg" },
  { primary: "ridges", common: ["rdgs"], standard: "rdgs" },
  { primary: "river", common: ["riv", "rvr", "rivr"], standard: "riv" },
  { primary: "road", common: ["rd"], standard: "rd" },
  { primary: "roads", common: ["rds"], standard: "rds" },
  { primary: "route", common: ["rte"], standard: "rte" },
  { primary: "row", common: ["row"], standard: "row" },
  { primary: "rue", common: ["rue"], standard: "rue" },
  { primary: "run", common: ["run"], standard: "run" },
  { primary: "shoal", common: ["shl"], standard: "shl" },
  { primary: "shoals", common: ["shls"], standard: "shls" },
  { primary: "shore", common: ["shr"], standard: "shr" },
  { primary: "shores", common: ["shrs"], standard: "shrs" },
  { primary: "skyway", common: ["skywy"], standard: "skwy" },
  { primary: "spring", common: ["spg", "spng", "sprng"], standard: "spg" },
  { primary: "springs", common: ["spgs", "spngs"], standard: "spgs" },
  { primary: "spur", common: ["spur", "spurs"], standard: "spur" },
  { primary: "square", common: ["sq", "sqr", "sqre", "squ"], standard: "sq" },
  { primary: "squares", common: ["sqrs", "sqs"], standard: "sqs" },
  { primary: "station", common: ["sta", "statn", "stn"], standard: "sta" },
  { primary: "stravenue", common: ["strav", "straven", "stravn", "strvn"], standard: "stra" },
  { primary: "stream", common: ["strm"], standard: "strm" },
  { primary: "street", common: ["st", "strt"], standard: "st" },
  { primary: "streets", common: ["sts"], standard: "sts" },
  { primary: "summit", common: ["smt", "sumit", "summitt"], standard: "smt" },
  { primary: "terrace", common: ["ter", "terr"], standard: "ter" },
  { primary: "throughway", common: ["thruwy"], standard: "trwy" },
  { primary: "trace", common: ["trce", "trc"], standard: "trce" },
  { primary: "track", common: ["trak", "trk", "trks"], standard: "trak" },
  { primary: "trafficway", common: ["trafwy"], standard: "trfy" },
  { primary: "trail", common: ["tr", "trl", "trls"], standard: "trl" },
  { primary: "trailer", common: ["trlr", "trlrs"], standard: "trlr" },
  { primary: "tunnel", common: ["tunl", "tunls", "tunnels", "tunnl"], standard: "tunl" },
  { primary: "turnpike", common: ["tpk", "tpke", "trnpk", "trpk", "turnpk"], standard: "tpke" },
  { primary: "underpass", common: ["upas"], standard: "upas" },
  { primary: "union", common: ["un"], standard: "un" },
  { primary: "unions", common: ["uns"], standard: "uns" },
  { primary: "valley", common: ["valy", "vally", "vlly"], standard: "vly" },
  { primary: "valleys", common: ["vlys"], standard: "vlys" },
  { primary: "viaduct", common: ["vdct", "viadct"], standard: "via" },
  { primary: "view", common: ["vw"], standard: "vw" },
  { primary: "views", common: ["vws"], standard: "vws" },
  { primary: "village", common: ["vill", "villag", "villg", "vlliage"], standard: "vlg" },
  { primary: "villages", common: ["vlgs"], standard: "vlgs" },
  { primary: "ville", common: ["vl"], standard: "vl" },
  { primary: "vista", common: ["vist", "vst", "vsta"], standard: "vis" },
  { primary: "walk", common: ["walk", "walks"], standard: "walk" },
  { primary: "wall", common: ["wall"], standard: "wall" },
  { primary: "way", common: ["wy"], standard: "way" },
  { primary: "ways", common: ["ways"], standard: "ways" },
  { primary: "well", common: ["wl"], standard: "wl" },
  { primary: "wells", common: ["wls"], standard: "wls" }
];

/**
 * USPS I4 Directional abbreviations
 * Source: https://pe.usps.com/text/pub28/pub28api_007.htm
 */
export const USPS_I4_DIRECTIONALS: { [key: string]: string } = {
  n: "n",
  north: "n",
  ne: "ne",
  northeast: "ne",
  s: "s",
  south: "s",
  se: "se",
  southeast: "se",
  sw: "sw",
  southwest: "sw",
  e: "e",
  east: "e",
  w: "w",
  west: "w"
};

/**
 * USPS Official Secondary Unit Designators
 * Source: https://pe.usps.com/text/pub28/pub28apc_003.htm
 */
export const USPS_SECONDARY_UNIT_DESIGNATORS: { [key: string]: string } = {
  'apartment': 'apt',
  'apt': 'apt',
  'basement': 'bsmt',
  'bsmt': 'bsmt',
  'building': 'bldg',
  'bldg': 'bldg',
  'department': 'dept',
  'dept': 'dept',
  'floor': 'fl',
  'fl': 'fl',
  'front': 'frnt',
  'frnt': 'frnt',
  'hangar': 'hngr',
  'hngr': 'hngr',
  'lobby': 'lbby',
  'lbby': 'lbby',
  'lot': 'lot',
  'lower': 'lowr',
  'lowr': 'lowr',
  'office': 'ofc',
  'ofc': 'ofc',
  'penthouse': 'ph',
  'ph': 'ph',
  'pier': 'pier',
  'rear': 'rear',
  'room': 'rm',
  'rm': 'rm',
  'side': 'side',
  'slip': 'slip',
  'space': 'spc',
  'spc': 'spc',
  'stop': 'stop',
  'suite': 'ste',
  'ste': 'ste',
  'trailer': 'trlr',
  'trlr': 'trlr',
  'unit': 'unit',
  'upper': 'uppr',
  'uppr': 'uppr',
  '#': '#'
};
